### ISSUE TITLE
Login to ms-teams fails after supplying the 'oauth' response uri

### ISSUE THREAD

**Issue by ivy-rew** [EionRobb/purple-teams#1]
hi @EionRobb 

I'm so glad you are initiating a ms-teams integration for Pidgin. So we don't have to run the heavy electron app for simple chats.

I've built the plugin here and added it to my LTS pidgin 2.13. After authentication myself in the browser and pasting the success URI back to the messagebox however, the login fails without any response. 

Is the plugin designed to run with pidgin 2? Or do I have to build pidgin3 (which is quite a burden on my Ubuntu/Mint).
Can I get logs or inspect what's going wrong throughout the login procedure?

**Comment by EionRobb** [comment]
Thanks for giving a go at trying out the plugin. It's early days yet, and a bit rough around the edges, but I'm trying to use it as my daily driver to motivate me to fix things as they come up! 

So far the plugin is only designed for pidgin2 (there's some pidgin3 things in there that's come over from the skypeweb plugin, but that was from a decade ago when the two code bases were fairly similar)

It could be that I'm still being a bit lazy and have some hard-coded APAC domains instead of correctly detecting regional servers? It might also be that its successfully logged in but thinks it hasn't for some raisin. 

A few different options of varying level to try debug this. Can you either: 
- grab a debug log from Help->Debug Window from the buddy list as you try reconnect to the account, or
- connect the account to a proxy server (eg the excellent Charles Proxy) and try to debug or send through the capture to my email, or
- create a guest login that i can access to try login to to see if somethings broken 

Just to check, are you logging into the main tenant or into a guest on another tenant? Are you using your main email address or the onmicrosoft.com domain?

**Comment by EionRobb** [comment]
Thanks for the debug log, and thanks for your email too :)

When you got the login popup webpage, did it ask you to pick an account, and did you chose your @axonivy.com work address?

Can you try specifying "axonivy.onmicrosoft.com" as the tenant, and also try not specifying a tenant by just leaving that field blank?

That "GuestUserNotRedeemed" message seems to come from the server thinking you're a guest user on that Teams account, rather than a regular user, either because of the tenant setting or from logging in with a personal microsoft account instead of the business one - or maybe there's something else going on entirely :)

**Comment by EionRobb** [comment]
Oh, your tenant should be "axonactivegroup.onmicrosoft.com" or "axonactivegroup", rather than "axonivy"
I'm not sure of a good way to be able to look that up just yet - maybe there's another API call I can do to find the right tenant ID that your email has access to, somehow...

**Comment by ivy-rew** [comment]
Yes, you are totally right. It's really just about picking the right tenant. Having switched to 'axonactivegroup', the contacts show up and it allows me to experiment with the current plugin state. Thanks you so much.
![pidginTenant](https://user-images.githubusercontent.com/15085693/163328013-d9d4757c-f36e-447e-874f-3bf632383311.png)

So I'd vote for the future, that there is some help available for the end user to get the tenant right. In theory I know that we have some kind of group account over several companies, but didn't know where to get the right qualifier to name it.

However, I know you just started this project. And maybe there are more important things to do first. At any rate, thanks for your work.

**Comment by DanielSiepmann** [comment]
Thanks for providing the plugin, so I don't need to have another broken chat app but can use Pidgin.

I've the same issue, also same log entries.
```
(13:48:01) connection: Connection error on 0x34850b0 (reason: 2 description: Login error: Guest user OID is missing. User is not redeemed. (code 0))
(13:48:01) jabber: jabber_actions: have pep: YES
(13:48:01) account: Disconnecting account <my account name> (0x1dfeb40)
(13:48:01) connection: Disconnecting connection 0x34850b0
```
I am a noob regarding Microsoft and the system. I have a personal and a work account at Microsoft with the same E-Mail Address.
But the Microsoft Team Instance is from one of our customers, not from us.

Would be happy if you can provide info regarding the Microsoft stuff, so I know how to properly log in.
