### ISSUE TITLE
Unable to receive messages. 

### ISSUE THREAD

**Issue by BC801** [EionRobb/purple-teams#43]
I am no longer able to receive messages. I can send messages and others are able to receive. But messages sent to me either in a chat or in a direct message I cannot receive them anymore. They do populate however after restarting Pidgin. I tried removing the add on and adding it back. Was working flawlessly till this morning.

**Comment by greatquux** [comment]
Yeah, I can confirm it seems like the messages may or may not come in intermittently or with a long delay (sometimes minutes, sometimes hours). In the debug log for teams I am also seeing though I'm not sure if those were there before the issues.

(08:48:43) certificate/x509/tls_cached: Peer cert did NOT match cached
(08:48:43) teams: Error parsing response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>

(snip, bunch of css)

**Comment by EionRobb** [comment]
Hopefully just a temporary issue and all ok now?  (Please re-open this issue if it's still a problem!)
